### ISSUE TITLE
Mixpanel isn't geolocating users/events

### ISSUE THREAD

**Issue by f2prateek** [segment-integrations/integration-mixpanel#2]
Mixpanel uses the IP address to geolocate users/events, but users have reported they don't see this information showing up in Mixpanel, so I think we may not be sending these correctly. 
From the HTTP Api docs - it looks like there are three ways to send an IP address.

1. As an `ip` query parameter in the URL (for `/track` endpoint).
2. As an `ip` property
```json
{
    "event": "Level Complete",
    "properties": {
        "Level Number": 9,
        "distinct_id": "13793",
        "token": "e3bc4100330c35722740fb8c6f5abddc",
        "time": 1358208000,
        "ip": "203.0.113.9"
    }
}
```
3. As `$ip` in `/engage` endpoint.
```json
{
    "$token": "36ada5b10da39a1347559321baf13063",
    "$distinct_id": "13793",
    "$ip": "123.123.123.123",
    "$set": {
        "Address": "1313 Mockingbird Lane"
    }
}
```

Might need to review how we send this info.
For instance, I think this line - https://github.com/segmentio/integration-mixpanel/blob/master/lib/index.js#L231 - should be `$ip` (or append the `ip` as a query parameter in the URL).

**Comment by hankim813** [comment]
Closed for inactivity/irrelevance. Please reopen if it's still an issue!
